// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchPingNodes(arg1, arg2) {
  return window['go']['main']['App']['BatchPingNodes'](arg1, arg2);
}

export function CheckGeoDatabases() {
  return window['go']['main']['App']['CheckGeoDatabases']();
}

export function CheckInstalledCores() {
  return window['go']['main']['App']['CheckInstalledCores']();
}

export function CheckIsAdmin() {
  return window['go']['main']['App']['CheckIsAdmin']();
}

export function ClearLiveLogs() {
  return window['go']['main']['App']['ClearLiveLogs']();
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function ConnectVPN(arg1, arg2) {
  return window['go']['main']['App']['ConnectVPN'](arg1, arg2);
}

export function DetectDefaultGateway() {
  return window['go']['main']['App']['DetectDefaultGateway']();
}

export function DisconnectVPN() {
  return window['go']['main']['App']['DisconnectVPN']();
}

export function DownloadCoreBinary(arg1, arg2) {
  return window['go']['main']['App']['DownloadCoreBinary'](arg1, arg2);
}

export function FetchGitHubReleasesNative(arg1, arg2) {
  return window['go']['main']['App']['FetchGitHubReleasesNative'](arg1, arg2);
}

export function FetchPresetDetails(arg1) {
  return window['go']['main']['App']['FetchPresetDetails'](arg1);
}

export function FetchPublicIPInfo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FetchPublicIPInfo'](arg1, arg2, arg3, arg4);
}

export function FetchRoutingPresets() {
  return window['go']['main']['App']['FetchRoutingPresets']();
}

export function GenerateCryptoKeys() {
  return window['go']['main']['App']['GenerateCryptoKeys']();
}

export function GenerateProxyURI(arg1) {
  return window['go']['main']['App']['GenerateProxyURI'](arg1);
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetCoreDLLVersion() {
  return window['go']['main']['App']['GetCoreDLLVersion']();
}

export function GetDefaultGateways() {
  return window['go']['main']['App']['GetDefaultGateways']();
}

export function GetDefaultRoutingRules() {
  return window['go']['main']['App']['GetDefaultRoutingRules']();
}

export function GetInstalledCoresDetails() {
  return window['go']['main']['App']['GetInstalledCoresDetails']();
}

export function GetLiveLogs() {
  return window['go']['main']['App']['GetLiveLogs']();
}

export function GetNetworkAdapters() {
  return window['go']['main']['App']['GetNetworkAdapters']();
}

export function GetSecuritySchema(arg1) {
  return window['go']['main']['App']['GetSecuritySchema'](arg1);
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ParseProxyURI(arg1) {
  return window['go']['main']['App']['ParseProxyURI'](arg1);
}

export function ProbeHotspotPairingServer(arg1) {
  return window['go']['main']['App']['ProbeHotspotPairingServer'](arg1);
}

export function ProxyPingActive(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ProxyPingActive'](arg1, arg2, arg3, arg4, arg5);
}

export function ReadStoreData(arg1) {
  return window['go']['main']['App']['ReadStoreData'](arg1);
}

export function ReloadCoreDLL() {
  return window['go']['main']['App']['ReloadCoreDLL']();
}

export function RequestAdminElevation() {
  return window['go']['main']['App']['RequestAdminElevation']();
}

export function RequestHotspotPairingWithPIN(arg1, arg2, arg3) {
  return window['go']['main']['App']['RequestHotspotPairingWithPIN'](arg1, arg2, arg3);
}

export function SaveStoreData(arg1, arg2) {
  return window['go']['main']['App']['SaveStoreData'](arg1, arg2);
}

export function StartDragWindow() {
  return window['go']['main']['App']['StartDragWindow']();
}

export function StartLANProxy(arg1, arg2) {
  return window['go']['main']['App']['StartLANProxy'](arg1, arg2);
}

export function StopLANProxy() {
  return window['go']['main']['App']['StopLANProxy']();
}

export function UpdateGeoDatabases() {
  return window['go']['main']['App']['UpdateGeoDatabases']();
}

export function ValidateSecurityConfig(arg1) {
  return window['go']['main']['App']['ValidateSecurityConfig'](arg1);
}
