// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function BatchPingNodes(arg1:string,arg2:number):Promise<string>;

export function CheckGeoDatabases():Promise<Record<string, any>>;

export function CheckInstalledCores():Promise<Record<string, boolean>>;

export function CheckIsAdmin():Promise<boolean>;

export function ClearLiveLogs():Promise<void>;

export function CloseWindow():Promise<void>;

export function ConnectVPN(arg1:string,arg2:string):Promise<Record<string, any>>;

export function DetectDefaultGateway():Promise<string>;

export function DisconnectVPN():Promise<Record<string, any>>;

export function DownloadCoreBinary(arg1:string,arg2:string):Promise<boolean>;

export function FetchGitHubReleasesNative(arg1:string,arg2:boolean):Promise<Array<Record<string, any>>>;

export function FetchPresetDetails(arg1:string):Promise<string>;

export function FetchPublicIPInfo(arg1:number,arg2:string,arg3:string,arg4:number):Promise<string>;

export function FetchRoutingPresets():Promise<string>;

export function GenerateCryptoKeys():Promise<string>;

export function GenerateProxyURI(arg1:string):Promise<string>;

export function GetConnectionStatus():Promise<Record<string, any>>;

export function GetCoreDLLVersion():Promise<string>;

export function GetDefaultGateways():Promise<Array<string>>;

export function GetDefaultRoutingRules():Promise<string>;

export function GetInstalledCoresDetails():Promise<Record<string, services.CoreDetails>>;

export function GetLiveLogs():Promise<Array<string>>;

export function GetNetworkAdapters():Promise<string>;

export function GetSecuritySchema(arg1:string):Promise<string>;

export function MinimizeWindow():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function ParseProxyURI(arg1:string):Promise<Record<string, any>>;

export function ProbeHotspotPairingServer(arg1:string):Promise<string>;

export function ProxyPingActive(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number):Promise<string>;

export function ReadStoreData(arg1:string):Promise<string>;

export function ReloadCoreDLL():Promise<Record<string, any>>;

export function RequestAdminElevation():Promise<boolean>;

export function RequestHotspotPairingWithPIN(arg1:string,arg2:number,arg3:string):Promise<string>;

export function SaveStoreData(arg1:string,arg2:string):Promise<boolean>;

export function StartDragWindow():Promise<void>;

export function StartLANProxy(arg1:number,arg2:number):Promise<Record<string, any>>;

export function StopLANProxy():Promise<boolean>;

export function UpdateGeoDatabases():Promise<boolean>;

export function ValidateSecurityConfig(arg1:string):Promise<boolean>;
